version: '3'

services:
  server-test:
    container_name: server-test
    image: node:latest
    working_dir: /usr/src/app
    volumes:
      - ./server-test:/usr/src/app
    ports:
      - "3000:3000"
    command: "npm start"
